name = "rootrecord-ava"
main = "src/worker.js"
compatibility_date = "2026-08-05"
workers_dev = true
account_id = "2b317e91da019f4fdb854e3b8e26fa94"

routes = [
  { pattern = "rootrecord.info/ava", zone_name = "rootrecord.info" },
  { pattern = "rootrecord.info/ava/*", zone_name = "rootrecord.info" },
  { pattern = "ava.rootrecord.info", zone_name = "rootrecord.info" },
  { pattern = "ava.rootrecord.info/*", zone_name = "rootrecord.info" }
]

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
html_handling = "none"
not_found_handling = "404-page"
